### ISSUE TITLE
No way to delete credentials

### ISSUE THREAD

**Issue by falsovsky** [vtsykun/packeton#104]
### Description

Hello,

While testing packeton to see if it would work for my requirements, I first added a composer auth.conf to the "My Credentials" to testing.

After that, I added a new SSH based credentials and wanted to delete the other record of auth.conf, but it doesnt seem to be any way to delete them.

Can it be done directly on the database? Or is there any other way that im missing?

### Can you reproduce the bug on the Packeton demo site?

Yes

### Database

SQLite

### How are you running Packeton?

Docker

**Comment by vtsykun** [comment]
Yes, you can directly delete from table `ssh_credentials` 
this is a missing feature. this will be fixed in the next release.
