### ISSUE TITLE
Composer.json examples?

### ISSUE THREAD

**Issue by hotrush** [vtsykun/packeton#11]
Hi.

Read the docs and didn't understand how to use it and install private packages, could you please provide any example for composer.json file?

**Comment by vtsykun** [comment]
Hi,
The adding a new package works exactly the same as https://packagist.org.
The typical `composer.json` may looks as:

```json
{
    "name":"youvendor/packege-name",
    "autoload":{
        "psr-4":{
            "YouVendorName\\":"src"
        }
    },
    "require":{
        "php": ">=7.0"
    }
}
```
Put it to your git or other VCS repository and commit it. Then hit the submit button in the UI menu.
If `composer.json` is not a valid, you will see a validation message.

![Screenshot from 2020-03-03 20-24-56](https://user-images.githubusercontent.com/21358010/75802239-7866db00-5d8d-11ea-9f92-29cd50104c98.png)

**Comment by hotrush** [comment]
@vtsykun thanks for response, but i wanted to know what to add in composer.json when i want to install a private package from packeton, i think that regular `composer require myrepo/mypackage` won't work here)

**Comment by vtsykun** [comment]
Ahh ok, in the first you need to add the private repository into `composer.json`, for example
```
{
    "repositories": {
        "youcompany": {
            "type": "composer",
            "url": "https://packages.youcompany.org"
        }
    },
    "require": {
        "youvendor/private-package": "^1.2"
    }
}
```

Also you need to authenticate to access their Composer repository, for example to enter credentials run command:

```
composer config --global --auth http-basic.packages.youcompany.org admin <you api token>
```

You can also find an example on the about page (link for a demo https://pkg.okvpn.org/about)

**Comment by hotrush** [comment]
@vtsykun thanks, will try
