### ISSUE TITLE
Magento API_V1 Proxy/mirror causing issues

### ISSUE THREAD

**Issue by robinero** [vtsykun/packeton#111]
### Description

Hey,

I've encountered an issue with the mirror/proxy when trying to pull-through Magento's repository packages.
Although I'm not sure if it's Magento's repo or if this is an issue with more API_V1 repo's.

Depending on the setting "Disable Composer API v2" it produces different errors and results.
This affects all packages pulled from the Magento repo, but I'm using `magento/module-admin-adobe-ims` as an example.

When "Disable Composer API v2" is set to "No":
Running `composer update magento/module-admin-adobe-ims -vvv` will result in the following:
```
Downloading https://packeton.tld/mirror/magento/p2/magento/module-admin-adobe-ims.json
[200] https://packeton.tld/mirror/magento/p2/magento/module-admin-adobe-ims.json
...
Installs: magento/module-admin-adobe-ims:100.5.0
Downloading magento/module-admin-adobe-ims (100.5.0)
Downloading https://packeton.tld/mirror/magento/zipball/magento/module-admin-adobe-ims/100.5.0.0/.zip
[404] https://packeton.tld/mirror/magento/zipball/magento/module-admin-adobe-ims/100.5.0.0/.zip
...
Trying the next URL for magento/module-admin-adobe-ims
...
```

I'm guessing this happens because the `reference` field from the json file is null, but I'm not sure:
```json
{
    "packages": {
        "magento/module-admin-adobe-ims": [
            {
                "name": "magento/module-admin-adobe-ims",
                ...
                "dist": {
                    "type": "zip",
                    "url": "https://repo.magento.com/archives/magento/module-admin-adobe-ims/magento-module-admin-adobe-ims-100.5.0.0.zip",
                    "reference": null,
                    "shasum": "bdacd08b88950e76da2014f6382f42e05950d006"
                },
                ..
                "uid": "58111a04fe161cd92c9d3aec8c16cfa1"
            },
  ...
```

Using the shasum as the ZIP name I can reach the zip archive and grab it: `https://packeton.tld/mirror/magento/zipball/magento/module-admin-adobe-ims/100.5.0.0/bdacd08b88950e76da2014f6382f42e05950d006.zip`

When "Disable Composer API v2" is set to "Yes":
Running `composer update magento/module-admin-adobe-ims -vvv` will result in the following:

```
Downloading https://packeton.tld/mirror/magento/pkg/magento/module-admin-adobe-ims%2482468a54b2e6292a948243c711e8a8ed1a3c2c82d3d4fafb64d165e0b6becca1.json
[200] https://packeton.tld/mirror/magento/pkg/magento/module-admin-adobe-ims%2482468a54b2e6292a948243c711e8a8ed1a3c2c82d3d4fafb64d165e0b6becca1.json
...
[Composer\Repository\RepositorySecurityException]
The contents of https://packeton.tld/mirror/magento/pkg/magento/module-admin-adobe-ims%2482468a54b2e6292a948243c711e8a8ed1a3c2c82d3d4fafb64d165e0b6becca1.json do not match its signature.
This could indicate a man-in-the-middle attack or e.g. antivirus software corrupting files. Try running composer again and report this if you think it is a mistake.
```
Reference: https://github.com/composer/composer/blob/11879ea737978fabb8127616e703e571ff71b184/src/Composer/Repository/ComposerRepository.php#L1471

The error is caused by the checksum not matching, this is because the provider-includes sets a "sha256" based on a file where every `/` is escaped as such: `\/`, however the file (`module-admin-adobe-ims%2482468a54b2e6292a948243c711e8a8ed1a3c2c82d3d4fafb64d165e0b6becca1.json`) provided by Packeton does not contain the escaped values, causing a mismatch.

To recreate this issue you need Magento credentials to access their (opensource) repo, if you need any tokens I can supply them.

The Magento mirror is added as shown in this git repo's documentation example:
```yaml
mirrors:
  magento:
    url: https://repo.magento.com/
    http_basic:
      username: xxx
      password: xxx
```

### Can you reproduce the bug on the Packeton demo site?

Not applicable

### Database

PostgreSQL

### How are you running Packeton?

docker

**Comment by vtsykun** [comment]
Hi 
The first error was fixed. I added prefix `ref` to mirror url to avoid 404 error `/mirror/firegento/zipball/%package%/%version%/ref%reference%.%type%` if `%reference%` is empty.

```
[404] https://packeton.tld/mirror/magento/zipball/magento/module-admin-adobe-ims/100.5.0.0/.zip

After
https://packeton.tld/mirror/magento/zipball/magento/module-admin-adobe-ims/100.5.0.0/ref.zip
```

The second errors happens, because to use composer v1 api need to run synchronization to download all providers includes.
For example the cache dir `/data/composer/proxy-meta/<name>/package/oro/` must contains the packages with sha256 hash. You can try to run "Force recync" to do it 
![Selection_1457](https://user-images.githubusercontent.com/21358010/235302191-a6453ef8-ea78-4702-ad4c-729a89d872bb.png)
