### ISSUE TITLE
Personal Access Tokens not working

### ISSUE THREAD

**Issue by rabauss** [vtsykun/packeton#117]
### Description

In Docker Version 2.2 the personal access tokens are not working at all for normal users.

On `composer install` we get the error:
```
Failed to download xxxx from dist: The "https://packeton.yyyy/zipball/xxxx/hash.zip" file could not be downloaded (HTTP/2 500 )
    Now trying to download from source
```
And on `composer update` we get:
```
The "https://packeton.yyyy/packages.json" file could not be downloaded (HTTP/2 500 ):                                         
  {"status":500,"detail":"Internal Server Error","title":"Internal Server Error","type":"https://tools.ietf.org/html/rfc2616#section-10"}
```

### Can you reproduce the bug on the Packeton demo site?

None

### Database

MySQL

### How are you running Packeton?

Docker Image with Packeton 2.2

**Comment by vtsykun** [comment]
Hi, does not reproduce on demo 

Can you check `var/log/prod.log` application logs? 

```
cat var/log/prod.log | grep -i -E '(critical|error)'
```
