### ISSUE TITLE
Api authorization

### ISSUE THREAD

**Issue by bajki** [vtsykun/packeton#14]
Hi, im getting this message for Gitlab Packagist service.
Test failed. {"status":"error","message":"Authorization Required"}

 https://pkg.okvpn.org/api/update-package?username=admin&apiToken=mdO9xasItyv2ECA3Ugk5

Request headers:
Content-Type: application/json
X-Gitlab-Event: Service Hook

Thanks

**Comment by vtsykun** [comment]
Hi,
I updated API to support packagist.org authorization format  
```
https://pkg.okvpn.org/api/update-package?username=admin&apiToken=mdO9xasItyv2ECA3Ugk5
```
You can testing on the latest docker image
