### ISSUE TITLE
New maintainer role

### ISSUE THREAD

**Issue by ulentini** [vtsykun/packeton#15]
Hello, we're deployng Packeton for our company, and we would find really useful a new role: maintainer.
Since all of the developers in our company should be able to browse all packages or submit, edit and update new ones.
We're forking it and we're gonna try to implement it ourselves, would you be interested in a pull request?

**Comment by vtsykun** [comment]
Hi @ulentini 
Yes, the PR is acceptable. I am thinking it will useful feature for other developers. Thank you!
