### ISSUE TITLE
When creating package via API, there is no way to specify Composer Credentials

### ISSUE THREAD

**Issue by mikk150** [vtsykun/packeton#157]
When creating package via API there is no way to specify Composer Credentials like in web package submit

**Comment by vtsykun** [comment]
Fixed. Example usage

```
{
  "repository": "git@github.com:sonata-project/SonataSeoBundle.git",
  "credentials": 4
}
```

**Comment by mikk150** [comment]
Yes, I added all my packages to packeton via this API.. it was pretty fast(Given I have 150 packages to add, and adding them manually would have been really tedious)

**Comment by vtsykun** [comment]
It makes sense to do mass import packages from GitHub / VCS /Satis or other composer repository. Currently supported only a new repos synchronization (via webhook when user push a new composer.json) from VCS via oauth2 integration https://docs.packeton.org/oauth2.html
