### ISSUE TITLE
Uncaught PHP Exception TypeError: "Packeton\Service\DistConfig::getFileName()

### ISSUE THREAD

**Issue by mikk150** [vtsykun/packeton#174]
### Description

```
request.CRITICAL: Uncaught PHP Exception TypeError: "Packeton\Service\DistConfig::getFileName(): Argument #2 ($version) must be of type string, null given, called in /app/src/Service/DistManager.php on line 200" at /app/src/Service/DistConfig.php line 85 {"exception":"[object] (TypeError(code: 0): Packeton\\Service\\DistConfig::getFileName(): Argument #2 ($version) must be of type string, null given, called in /app/src/Service/DistManager.php on line 200 at /app/src/Service/DistConfig.php:85)"} []
```

1. https://github.com/vtsykun/packeton/blob/master/src/Service/DistManager.php#L191 `$versionName` could be `null`
2. https://github.com/vtsykun/packeton/blob/master/src/Service/DistManager.php#L200 can pass null on
3. https://github.com/vtsykun/packeton/blob/master/src/Service/DistConfig.php#L85 requires `$version` to exist
Boom :boom: 

### Can you reproduce the bug on the Packeton demo site?

None

### Database

MySQL

### How are you running Packeton?

In kubernetes

**Comment by vtsykun** [comment]
Fixed https://github.com/vtsykun/packeton/pull/175
