### ISSUE TITLE
Packeton review bot got a wrong composer.lock diff

### ISSUE THREAD

**Issue by vtsykun** [vtsykun/packeton#189]
### Description

See https://github.com/vtsykun/packeton/pull/187#issuecomment-1786873540

### Can you reproduce the bug on the Packeton demo site?

None

### Database

None

**Comment by p-makowski** [comment]
Hi @vtsykun 
I am not sure if it got wrong composer.lock. Branch in this PR was somehow not in sync with origin/master, review bot was active before I synced the branch with origin. 
I believe it works as expected, it was just my fault.
