### ISSUE TITLE
Admin users are ghost users

### ISSUE THREAD

**Issue by twommerce** [vtsykun/packeton#191]
### Description

Admin users are not listed under "Settings > My users" so there is no way to see all admin users., neither to maintain who has access as admin.

Moreover, it is not possible to delete admin that was just created using console method:

` packagist:user:manager  xyz --admin --delete 
10:37:52 CRITICAL  [console] Error thrown while running command "packagist:user:manager xyz --admin --delete". Message: "User not found or not exists in database" ["exception" => Symfony\Component\Console\Exception\LogicException^ { …},"command" => "packagist:user:manager xyz --admin --delete","message" => "User not found or not exists in database"]

                                            
  User not found or not exists in database  
`

### Can you reproduce the bug on the Packeton demo site?

None

### Database

None

### How are you running Packeton?

docker

**Comment by p-makowski** [comment]
Thank you @vtsykun for fast reaction!
