### ISSUE TITLE
Restrict access matrix group last version not working - 404 not found

### ISSUE THREAD

**Issue by magextensions** [vtsykun/packeton#208]
### Description

We get a 404 not found when we restrict a group with a access matrix for a package to the last available fixed version. For example : 1.0.1|1.0.2|1.0.3|1.0.4|1.0.5|1.0.6

 Downloading package/name (1.0.6)
 0/3 [>---------------------------]   0%    Failed to download package/name from dist: The "https://host/zipball/package/name/AAd581511ad42325bedffa5cb7caafa6844c1ec48695d.zip" file could not be downloaded (HTTP/2 404 ):
{"status":"error","message":"Not Found"}
    Now trying to download from source

When we create a new release in git with version 1.0.7 then 1.0.6 will work.

Is this a know bug? 

### Can you reproduce the bug on the Packeton demo site?

None

### Database

None

### Screenshots

![Screenshot at 2023-12-25 2](https://github.com/vtsykun/packeton/assets/29015984/1024b744-7f3e-4082-a039-a73205cfaed4)
![Screenshot at 2023-12-26 2](https://github.com/vtsykun/packeton/assets/29015984/398035d8-2031-4a46-bde8-c5cf1987b5f5)
![Screenshot at 2023-12-25](https://github.com/vtsykun/packeton/assets/29015984/382b4614-b166-4bc8-ba4a-58c68478ca24)

### How are you running Packeton?

php-fpm, nginx

**Comment by magextensions** [comment]
Did some debugging and it looks like that it is going wrong in the zipballAction function. isGranted === false at line 91.

**Comment by magextensions** [comment]
`    public function getVersionByReference(string $reference): ?Version
    {
        return $this->versions->findFirst(fn($k, $v) => $v->getReference() === $reference);
    }`

the reference has two results "dev-master" and "1.0.6"
findFirst returns dev-master and this version is not in the ACL

**Comment by magextensions** [comment]
is there also a way to only get released git versions in packeton ? and not the dev- branches ?

**Comment by vtsykun** [comment]
Hi @magextensions thank you for deep investigation, issue was fixed

**Comment by magextensions** [comment]
Hi @vtsykun ,

Thank you for the fast fix and nice software.
