### ISSUE TITLE
Packeton is not respecting config.json (composer)

### ISSUE THREAD

**Issue by vigri** [vtsykun/packeton#23]
Hi there,

I've setup a Packeton instance in my local network.
When I try to add a package from a server which is on my local network too I get an error:

![image](https://user-images.githubusercontent.com/2580723/85023420-ff8d6280-b174-11ea-8bf6-bd60150c2d60.png)

I'm aware of the risks, but since this is a test-setup in my local network this shouldn't be a problem.

According to the manual `secure-http` should be set to `false` inside `config.json` to enable http-connections.

https://github.com/vtsykun/packeton#ssh-key-access-and-composer-oauth-token says the `.config.json` should be placed inside the root-directory of the app under `.composer/config.json`

This is what my `config.json` looks like
```
{
    "config": {
        "secure-http": false
    }
}
```

Unfortunately the error remains.

Can you tell me please how to debug this error further?

**Comment by vtsykun** [comment]
Hi, you need to place this file relative to the home directory of web-server, i. e. `~/.composer/config.json, /var/www/.composer/config.json`, but not inside the root-directory of the application.

**Comment by vtsykun** [comment]
You need to use `$_SERVER['HOME']`  Please, can you check `phpinfo` to see web home dir?

![Selection_202](https://user-images.githubusercontent.com/21358010/85042810-50608380-b194-11ea-8952-25e4f38fd950.png)
