### ISSUE TITLE
help or clarification - cache and show mirrored packages into directory

### ISSUE THREAD

**Issue by moneef** [vtsykun/packeton#236]
Hello,
when trying to mirror/proxy a repo it doesn't show in package directory when i click on Browse it doesn't show anything

<img width="940" alt="1" src="https://github.com/vtsykun/packeton/assets/6404057/98b8ba94-ce96-4a48-84ed-29abbec3c770">
<img width="926" alt="2" src="https://github.com/vtsykun/packeton/assets/6404057/40c1234c-1d2a-42b6-ba9d-79fd13ea6adb">
<img width="785" alt="3" src="https://github.com/vtsykun/packeton/assets/6404057/ae608dd7-c519-478f-8f75-f5e344102d93">
<img width="812" alt="4" src="https://github.com/vtsykun/packeton/assets/6404057/ba4539ab-8ffc-4b84-823b-7be9a505183f">

**Comment by vtsykun** [comment]
No, this feature is not supported yet. (as I know the paid packages.com has this feature - union all mirrored and submitted packages together). For mirrored and submitted packages you must use two different repository URLs in composer.json.

**Comment by moneef** [comment]
is there a plan to implement this feature? 
i would like to help but i don't know how and where to start. any advice will be appreciated

**Comment by vtsykun** [comment]
> is there a plan to implement this feature?

you can use multiple repositories in composer.json. I'd like to keep separate url for minorring packages and for main repository. It seems difficult to merge together the metadata of two repositories without performance degradation. 


```json
    "repositories": [
        {
            "type": "composer",
            "url": "https://example.com"
        },
        {
            "type": "composer",
            "url": "https://example.com/mirror/amasty"
        }
    ],
```

**Comment by jg-development** [comment]
I kind of added a "proxy submit" for repos from proxy like magento and so on.
maybe this can help u:
https://github.com/jg-development/packeton/commit/fdf5d8608b4b33c843c1a470a240f74a779a017d

**Comment by vtsykun** [comment]
Now you can submit a proxy package to the central repository
![Selection_635](https://github.com/user-attachments/assets/653a6052-4610-4645-a8e9-882377f53207)
