### ISSUE TITLE
Bitbucket webhook not working

### ISSUE THREAD

**Issue by fabianderijk** [vtsykun/packeton#27]
We have installed packeton as a private package manager. Everything is working like it should, however, we cannot get the automatic updates to work.

We use a private bitbucket for our repositories (so not on bitbucket.com). Every time we add a webhook and this is fired we get a 406 error that says `{"status":"error","message":"Missing payload parameter"}`.

The request is being sent to: `https://packeton.<company>.ext/api/bitbucket?token=<user>:<token>` (where the url and username / token are obfuscated here). The payload is being sent (we can see it in bitbucket), the url is correct and the user exists and its token is valid. What is it that we are missing?

**Comment by fabianderijk** [comment]
I just taken a look at https://github.com/vtsykun/packeton/blob/master/src/Packagist/WebBundle/Controller/ApiController.php#L110 and it looks like a private bitbucket repo is not working. The only one is the bitbucket.org one or a custom, but that does not have the correct payload unfortunately. 

Ik will try to create a PR for this issue.

**Comment by bezio** [comment]
You may try this one for now: https://github.com/vtsykun/packeton/pull/40
