### ISSUE TITLE
Unauthenticated package metadata access

### ISSUE THREAD

**Issue by xelan** [vtsykun/packeton#28]
Thanks for your great work of continuing the open-source packagist app. Is there a way to allow package metadata read access without authentication (for all or for specific packages)?

**Comment by vtsykun** [comment]
Yes you can do it, but for it need to made a fork and update `security.yml` here https://github.com/vtsykun/packeton/blob/master/app/config/security.yml#L52

**Comment by xelan** [comment]
Great, thank you very much for your feedback @vtsykun :+1: So we'd need to change `ROLE_USER` to `IS_AUTHENTICATED_ANONYMOUSLY` in that path rule (e.g. by patching security.yml during deployment) and it should already work?

Best regards
Andreas

**Comment by vtsykun** [comment]
Hi @xelan 
Yes. Please notes that `zipball` path used for download package code from dist. If you need read-only access to the package metadata, you can split this rule in two
```yml
         - { path: (^(/packages.json$|/p/))+, role: IS_AUTHENTICATED_ANONYMOUSLY } # metadata read access
         - { path: (^(/zipball/|/downloads/))+, role: ROLE_USER } # *.zip download
```

**Comment by xelan** [comment]
Sounds great, thanks! I'll try that :smile:

**Comment by roelandg** [comment]
> Hi @xelan
> Yes. Please notes that `zipball` path used for download package code from dist. If you need read-only access to the package metadata, you can split this rule in two
> 
> ```yaml
>          - { path: (^(/packages.json$|/p/))+, role: IS_AUTHENTICATED_ANONYMOUSLY } # metadata read access
>          - { path: (^(/zipball/|/downloads/))+, role: ROLE_USER } # *.zip download
> ```

Hi @vtsykun  I tried your suggestion, however still got an "authorization Required" on /packages.json.

Any idea? Thanks! Btw, compliments for this nice fork!

**Comment by roelandg** [comment]
@vtsykun Nevermind. I figured, I had to allow anonymous access by altering the PackageController.

**Comment by anebi** [comment]
Hello,

@vtsykun may I ask you what exactly you changed in PakageController? I am looking to enable annonymouse access for packages too.

Thank you!
