### ISSUE TITLE
Public access to some packages?

### ISSUE THREAD

**Issue by Bashev** [vtsykun/packeton#286]
Is it possible to make some packages public listed without auth?

**Comment by vtsykun** [comment]
Currently not supported, but I can add public access support for sub-repositories settings.

Now endpoint `/packages.json` always return 401 code if the user has not provided an API key. I want to avoid different behavior with and without an API key if the user marks any package for public access.  

![Selection_591](https://github.com/user-attachments/assets/fc50866e-daae-4a1c-9d76-203b06664ab4)

What do you think about using subrepositories?  does this fit your use case?

**Comment by vtsykun** [comment]
Hi @Bashev 
I setup public access sub repository example.

https://demo.packeton.org/subrepository/9/update

![Selection_634](https://github.com/user-attachments/assets/3c6bd4f8-c100-40ec-866a-7a7d8cd31c70)

You may use path prefix to access to public repo

https://demo.packeton.org/repo1

Or separate host name

https://repo1.packeton.org/

**Comment by Bashev** [comment]
Thank you, i'll test you, but looks like more than enough! 

Respect!
