### ISSUE TITLE
Invalid credentials with packagist and LDAP

### ISSUE THREAD

**Issue by johnnybaida** [vtsykun/packeton#64]
Hello,
I have configured the project with two authentication providers: packagist and LDAP.

The LDAP provider works, but when I login with a local user (packagist) I get this message: "Invalid credentials."

<pre>
security:                
    providers:
        users_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                .....

        all_users:
            chain:
                providers: ['packagist','users_ldap'] # <- Load user/roles form default packagist and if not found - use ldap user
</pre>

It seems that the local user is being ignored!

Thanks and great job!

**Comment by vtsykun** [comment]
Fixed
