### ISSUE TITLE
Forcing https with docker

### ISSUE THREAD

**Issue by johnnybaida** [vtsykun/packeton#65]
Hello, 
How can I force the use of HTTPS protocol?
I am currently using docker and apache proxy, but the application makes HTTP calls.

The problem I have been experiencing is that when I login with HTTPS the page redirects to HTTP and remains on the login page, even though authentication was successful.

apache VirtualHost *:443
<pre>
      ...

      Protocols h2 http/1.1

      ProxyRequests on
      ProxyPreserveHost On
      ProxyPass / http://127.0.0.1:8188/
      ProxyPassReverse / http://127.0.0.1:8188/

      SSLProxyEngine On
      SSLProxyVerify none
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off
      SSLProxyCheckPeerExpire off

      ...
</pre>

Thanks and great job!

**Comment by vtsykun** [comment]
Hi, please add this line to VirtualHost config 

```
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
```

**Comment by johnnybaida** [comment]
It works. Thank you very much!!!

**Comment by roj1512** [comment]
For NGINX:

```
proxy_set_header X-Forwarded-Proto $scheme;
```
