### ISSUE TITLE
Question: Docker Image Release

### ISSUE THREAD

**Issue by johnnybaida** [vtsykun/packeton#67]
Hello,
again my congratulations on the project.

I was wondering when a new version is scheduled to be released on dockerhub. I am looking forward to try the latest changes. 
I see the demo version different from the one published on dockerhub.

Thanks again.

**Comment by vtsykun** [comment]
Hi @johnnybaida 
Do you mean stability release tag? 
Dockerhub the latest tag always synchronize with master via github action. `packeton/packeton:latest` 
https://github.com/vtsykun/packeton/blob/master/.github/workflows/docker.yaml

I'm testing a new feature on the demo, it's not in the master yet

**Comment by vtsykun** [comment]
The 2.1 version has been released. 

Thanks.
