### ISSUE TITLE
Support MonoRepos, sub-directory, artifacts repository type.

### ISSUE THREAD

**Issue by vtsykun** [vtsykun/packeton#68]
This feature is allow to use a mono repository, the Packeton must to split up it into single composer installable packages for each sub-directory. See comments for https://github.com/composer/packagist/issues/472

Todo List 
- [x] Support mono repos (#85)
- [x] Support uploading artifacts (https://github.com/vtsykun/packeton/pull/118)

Ref: #22

**Comment by ijry** [comment]
hi, any news on this?

**Comment by vtsykun** [comment]
Hi, ok I'll include this feature with more priority in the next release.
