### ISSUE TITLE
Auth for mirroring proxy

### ISSUE THREAD

**Issue by bergo** [vtsykun/packeton#77]
### Description

The ROLE_USER auth does not work for mirroring packages.  The composer return everytime:

Invalid credentials for 'https://xxx:yyy@php-pkg.mogic.com/mirror/<<package>>/packages.json', aborting.

The user has access over ACL group. The group has selected the allowed proxy. 

### Can you reproduce the bug on the Packeton demo site?

None

### Database

None

### How are you running Packeton?

We are running packeton in single container mode

**Comment by vtsykun** [comment]
Fixed!

**Comment by bergo** [comment]
Works now, thanks a lot.
