### ISSUE TITLE
Is there any api to add user/customer? 

### ISSUE THREAD

**Issue by sunilit42** [vtsykun/packeton#81]
Hello,

we are working on selling module and we are trying to provide package by composer

we are facing an issue with that, we don't have API to create user to allow to package

**Comment by vtsykun** [comment]
Hi @sunilit42 
Not yet. But I think it's easy to do and can include in the next release. API was inherited from Packagist.org, so I think it needs to be improved

**Comment by sunilit42** [comment]
@vtsykun can i know when next release happen?

we are trying to  selling extension, and customer can download using composer using free 
in that each customer wise a different composer package, is that possible with that? as I see only API missing

**Comment by vtsykun** [comment]
Yes, you can assign different packages to different customers. To reuse set of assigned packages used users groups. 
In the next 1-2 weeks I'll provider PR for this and you can able to use `latest` tag with Docker

**Comment by sunilit42** [comment]
@vtsykun have you added api?
how i can locally check it?

**Comment by vtsykun** [comment]
Hi @sunilit42 Still in progress. But I deploy dev feature branch to the demo, you can check 
https://demo.packeton.org/apidoc#swagger-ui

**Comment by MaheshLalwani-NextBits** [comment]
> Hi @sunilit42 Still in progress. But I deploy dev feature branch to the demo, you can check https://demo.packeton.org/apidoc#swagger-ui


@vtsykun Thank you, by when do you think this will be merged in the main branch?
