### ISSUE TITLE
Customer is able to install a package which is not assigned to him

### ISSUE THREAD

**Issue by MaheshLalwani-NextBits** [vtsykun/packeton#84]
### Description

I have created a customer and have not assigned him any package, still, i am able to install the package using composer require
below is a response from get customer

{
        "id": 6,
        "username": "customer4",
        "email": "customer4@mailinator.com",
        "enabled": true,
        "createdAt": "2023-03-10T08:11:04+00:00",
        "expireAt": "2023-03-31T00:00:00+00:00",
        "expiredUpdatesAt": "2023-03-31T00:00:00+00:00",
        "apiToken": "###########",
        "roles": [
            "ROLE_USER"
        ],
        "groups": [],
        "allowedPackages": [],
        "allowedProxies": [],
        "isMaintainer": false,
        "gravatarUrl": "https://www.gravatar.com/avatar/b5ff41c6ec6b2f14d8f7c275617767de?d=identicon",
        "fullAccess": false
    }

### Can you reproduce the bug on the Packeton demo site?

Yes

### Database

SQLite

### Screenshots

![image](https://user-images.githubusercontent.com/126144550/224294630-b4a587b2-4e75-48b3-9c1f-696689615090.png)

### How are you running Packeton?

Yes

**Comment by vtsykun** [comment]
Hi @MaheshLalwani-NextBits 

Does not reproduce on demo.

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://demo.packeton.org"
        }
    ],
    "require": {
        "php": ">=8.1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

2. Run `composer config --global --auth http-basic.demo.packeton.org customer4 6CzjMExRcNg2wt3D0dLb`
3. Run `composer require okvpn/satis-api -vvv`

Actual result
```
Reading /home/dev/.cache/composer/repo/https---demo.packeton.org/packages.json from cache
Using HTTP basic authentication with username "customer4"
Downloading https://demo.packeton.org/packages.json if modified
[200] https://demo.packeton.org/packages.json
Writing /home/dev/.cache/composer/repo/https---demo.packeton.org/packages.json into cache
Downloading https://demo.packeton.org/p2/okvpn/satis-api.json
Downloading https://demo.packeton.org/p2/okvpn/satis-api~dev.json
[404] https://demo.packeton.org/p2/okvpn/satis-api.json
[404] https://demo.packeton.org/p2/okvpn/satis-api~dev.json
Reading /home/dev/.cache/composer/repo/https---repo.packagist.org/packages.json from cache
Downloading https://repo.packagist.org/packages.json if modified
[200] https://repo.packagist.org/packages.json
Info from https://repo.packagist.org: #StandWithUkraine
Writing /home/dev/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p2/okvpn/satis-api.json
Downloading https://repo.packagist.org/p2/okvpn/satis-api~dev.json
[404] https://repo.packagist.org/p2/okvpn/satis-api.json
[404] https://repo.packagist.org/p2/okvpn/satis-api~dev.json
Downloading https://packagist.org/providers/okvpn/satis-api.json
[200] https://packagist.org/providers/okvpn/satis-api.json
Downloading https://packagist.org/search.json?q=okvpn%2Fsatis-api&type=
[200] https://packagist.org/search.json?q=okvpn%2Fsatis-api&type=

In PackageDiscoveryTrait.php line 355:
                                                                                                                                                
  [InvalidArgumentException]                                                                                                                    
  Could not find package okvpn/satis-api. It was however found via repository search, which indicates a consistency issue with the repository.  
```

Also user will not able to download any version 
```
https://demo.packeton.org/zipball/okvpn/satis-api/ee3190ba70610daa82db6de91a21009c40c1825f.zip?token=customer4:6CzjMExRcNg2wt3D0dLb
```

Thanks

**Comment by MaheshLalwani-NextBits** [comment]
@vtsykun 
i get this error  locally even if I assign the package to customer4


My composer.json 

{
    "repositories": [
        {
            "type": "composer",
            "url": "https://demo.packeton.org"
        }
    ],
    "require": {
        "php": ">=8.1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}


![image](https://user-images.githubusercontent.com/126144550/224299640-cacb9beb-2893-4f16-8d8a-16a7da8379a5.png)

**Comment by vtsykun** [comment]
Yes it's expected result, because customer4 not able to install with package

**Comment by MaheshLalwani-NextBits** [comment]
@vtsykun 
if you see the customer4 on the demo site I have assigned him all the ACL groups, in this case, he should be able to install correct?

please do le me know if i am missing something here


![image](https://user-images.githubusercontent.com/126144550/224302353-810a647a-dfe3-46c3-8427-0941441c2dc2.png)

**Comment by vtsykun** [comment]
> if you see the customer4 on the demo site I have assigned him all the ACL groups, in this case, he should be able to install correct?

The package must belong to these group.
![Selection_1345](https://user-images.githubusercontent.com/21358010/224303490-b4496e23-18c6-42ff-bf8e-53f3ddf2e58e.png)

**Comment by vtsykun** [comment]
The original question - the only reason this can happen is cache.

STR:
1. create two users: customer11, customer4
2. Assign all packages to customer11
3. Run `composer config --global --auth http-basic.demo.packeton.org customer11 H6RMIbkY1X2WdVpYGWXY`
4. Run `composer require okvpn/satis-api -vvv`
5. The package okvpn/satis-api was installed successfully  
6. Switch user `composer config --global --auth http-basic.demo.packeton.org customer4 6CzjMExRcNg2wt3D0dLb`
7. Run `composer require okvpn/satis-api -vvv`
8. The package okvpn/satis-api was installed successfully  but user not have access to okvpn/satis-api

It happens because composer use cache for user `customer11`. And it's not bug for packeton. 

Run with flag `--no-cache` if switch user locally. 

```
composer require okvpn/satis-api -vvv --no-cache
```

**Comment by vtsykun** [comment]
Hi @MaheshLalwani-NextBits  can you try to use the latest and confirm that was fixed? I made a small changes to reset cache if user was changed - must resolve this issue

**Comment by MaheshLalwani-NextBits** [comment]
@vtsykun  I verified with latest from main branch and this is fixed Thank you :)
