### ISSUE TITLE
Block storage

### ISSUE THREAD

**Issue by holantomas** [vtsykun/packeton#97]
Hi,
is there way to use block storage(AWS S3 like/compatible) to store zipballs? It's mandatory for FaaS deployment where persistent storage is unavailable like DigitalOcean App Platform.

**Comment by vtsykun** [comment]
Hi, block storage not supported. 
The zipballs can be created in real time at the request of the user using the composer archive or the `git archive`. The local disk storage used only as cache

**Comment by holantomas** [comment]
Ok, thanks
